
reloadConfig: '&aYou have reloaded the config'
noPermission: '&4You do not have the permission to execute this command'

noAvailableCommands: '&cYou have no available commands.'
invalidCommand: '&cInvalid command. Use &6/blackmarket help &cfor available commands.'
playersOnly: '&cOnly players can use this command.'
consoleOnly: '&cOnly the console can use this command.'

genericShopDisplayItemShowAmount: '&7Current selected amount: &a{amount}'
genericShopBuyLore: '&7Buy price: &a{amount}&7$'
genericShopSellLore: '&7Sell price: &c{amount}&7$'

##################
## BLACK MARKET ##
##################

blackMarketSpawnedTitle: '&1Black market available'
blackMarketSpawned: '&1The black market has spawned &csomewhere &1inside the spawn world. The market is operational for {minutes} minutes'
blackMarketLeave: '&1The black market has left the spawn world. They won`t be back for a couple of hours.'

openBlackmarketGUIHelpMessage: '&6/blackmarket open &e- Opens the black market GUI without walking to the NPC.'
noBlackmarket: '&cThe black market is not currently open'

blackMarketStatusHelpMessage: '&6/blackmarket status &e- Checks whether the black market is spawned or not.'
blackMarketOpen: '&aOPEN'
blackMarketClosed: '&cCLOSED'
blackMarketStatus: '&aThe black market is currently: {status}'

blackMarketItemName: '<GRADIENT:084CFB>{name}</GRADIENT:ADF3FD>'
blackMarketLore: '&7Sell this item for: &c{value}$'

#%
blackMarketSpawnChance: 50
#Minutes
blackMarketStayDuration: 30
blackMarketCooldown: 240

percentPriceDropPerItemSold: 0.00125

#NOTHING ~= 80%
#SCAM ~= 14%
#ROBBED ~= 3%
#MUGGED ~= 1%
#Value of 0 or less disables an event
eventChancesStack:
  NOTHING: 8000
  SCAM: 1400
  ROBBED: 300
  MUGGED: 100

#NOTHING ~= 70%
#SCAM ~= 21%
#ROBBED ~= 6%
#MUGGED ~= 3%
#Value of 0 or less disables an event
eventChancesWholeInv:
  NOTHING: 7000
  SCAM: 2100
  ROBBED: 600
  MUGGED: 300

warnPlayer: '&cThe black market allows you to sell items without taxes. &eCaution, &cwhile selling to the black market you have a chance of being &6scammed, &4robbed, &cor &4mugged &c(lose your whole inventory).'

scammedMinPercent: 1.5
scammedMaxPercent: 15.4

npcName: '&1Black market'
npcSkin: BikMoss
soldItemBlackmarket: '&7You have sold {amount} items to the black market for {value}$'

robbed: '&cThe sketchy dealer &6ran off &cafter inspecting your goods. You were &4not able &cto catch up to him.'
scammed: '&eAfter inspecting the money, you realize that &6{percent}%({value}) &eof it was fake. The person that you sold the items to &6claims to know nothing &eabout it.'
mugged: '&cAfter selling your items, you felt the presence of &4multiple armed thugs. &cYou had no choice but to give up your money you just made, and your inventory to survive.'


###################
## AUCTION HOUSE ##
###################

itemExpired: '&cOne of your items expired'
itemBought: '&aSomeone bought one of your items for {value}$ / {glcoins} GLCoins'
boughtItem: '&aYou`ve bought the listen item for {value}$ / {glcoins} GLCoins'
notEnoughFunds: '&cYou don`t {needed} for the current selected price. Balance: {balance}'

ahSellHelpMessage: '&6/ah sell [sell_value] [glcoins] &e- Lists the current item in your main hand in the auction house.'
ahSellSyntax: '&cUse - /ah sell [sell_value] [glcoins]'
ahSellMustHoldItem: '&7AH - &cYou must hold an item in your main hand'
ahSellInvalidPries: '&7AH - &cYou cannot have both values for sell_value and glcoins at 0.000 or lower'
ahSellNoMoreSpace: '&7AH - &cYou have too many items listed in the auction house currently'
ahSellListed: '&7AH - &aYou have successfully listed your item'

ahConfirm: '&7AH - &aPress again to confirm'

transactionNoLonger: '&cThis item is no longer available'

#Minutes
#720 minutes = 12 hours
ahItemExpireTime: 720

#The lore that will be displayed at the bottom of the original item's lore
ahListingItemLore:
  - ' '
  - '&cExpires on: {date}'
  - '&7Price: &a{price}$ &7(Left click)'
  - '&7GLCoins: &b{glcoins} &7(Shift right click)'

#These ones will be displayed under ahListingItemLore, message depending on if you're a buyer, or the person who posted the item
ahListingItemBuyer:
  - ' '
  - '&aLeft click to buy'

ahListingItemPublisher:
  - ' '
  - '&cRight click to retrieve'

#Used for button actions
extraMessages:
  cannotAccessShopCategory: 'Go to spawn and search for the npc, you poor fuck'