name: GLC-GUIS
main: com.deadshotmdf.GLC_GUIS.GLCGGUIS
authors: [ DeadshotMDF, Bodygiard1 ]
version: 1.0
api-version: 1.21
depend:
  - Vault
  - GLCoins-Server
libraries:
  - org.reflections:reflections:0.10.2
commands:
  shop:
    description: Opens the main shop GUI.
    usage: /shop
  csv:
    description: Generates csv files
    usage: /csv
