name: GLC-GUIS
main: com.deadshotmdf.GLC_GUIS.GLCGGUIS
authors: [ DeadshotMDF, Bodygiard1 ]
version: 1.0
api-version: 1.21
depend:
  - Vault
  - GLCoins-Server
libraries:
  - org.reflections:reflections:0.10.2
  - org.apache.poi:poi:5.2.3
  - org.apache.poi:poi-ooxml:5.2.3
commands:
  shop:
    description: Opens the main example GUI.
    usage: /shop
  glcguis:
